config/routes.rb
Rails.application.routes.draw do

resources :cocktails, only: [:index, :show, :new, :create] do

  resources :doses, only: [:new, :create, :destroy]

end

root 'cocktails#index'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end
  def new
    @cocktail = Cocktail.new
  end
  def create
    @cocktail = Cocktail.new(cocktails_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end
  def show
    find_cocktail
  end


  private

  def cocktails_params
    params.require(:cocktail).permit(:name)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [ :new, :create ]
  def new
    @dose = Dose.new
    @ingredients = Ingredient.all
  end
  def create
    @dose = @cocktail.doses.build(doses_params)
    if @dose.save
      redirect_to cocktails_path
    else
      render :new
    end
  end
  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to :back
  end


private

  def doses_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="padded">
  <h1>Liste des cocktails</h1>
  <div class="padded">
    <ul class="list-inline">
      <% @cocktails.each do |cocktail| %>
      <li>
      <%= link_to cocktail.name, cocktail_path(cocktail) %>
      </li>
      <% end %>
    </ul>
    </div>
  <%= link_to "Add a cocktail", new_cocktail_path , class: "btn btn-success"%>

</div>

app/views/cocktails/new.html.erb
<h1>Add a cocktail</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class="padded">
  <h1>Recette du <%= @cocktail.name %></h1>

  <ul>
    <% @cocktail.doses.each do |dose| %>
    <li>
      <%= dose.ingredient.name %> :
      <%= dose.description %> -
      <%=link_to "delete", cocktail_dose_path(@cocktail, dose), method: :delete %>
    </li>
    <% end %>
  </ul>
</div>
<%= link_to "Add an ingredient", new_cocktail_dose_path(params[:id]) , class: "btn btn-success"%>
<%= link_to "back", cocktails_path , class: "btn btn-success"%>

app/views/doses/new.html.erb
<h1>Add an ingredient</h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient%>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>
  <div class="container text_center">
    <%= render "shared/navbar" %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="" class="logo">
      <%= image_tag "logo.png"%>
    </a>

    <div class="navbar-wagon-pusher"></div>


    <%= link_to t(".top_call_to_action", default: "Add a cocktail"), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>